/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kingdom;

import java.awt.event.KeyEvent;

/**
 *
 * @author Eric
 */
public class GameSetup extends javax.swing.JFrame {

    /**
     * Creates new form KingdomOptions
     */
    public GameSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kingdomN = new javax.swing.JLabel();
        kingN = new javax.swing.JLabel();
        difficulty = new javax.swing.JLabel();
        easy = new javax.swing.JCheckBox();
        medium = new javax.swing.JCheckBox();
        hard = new javax.swing.JCheckBox();
        kingdomBox = new javax.swing.JTextField();
        kingBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        titleSetup = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 565, 377));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        kingdomN.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        kingdomN.setText("Kingdom Name");
        jPanel1.add(kingdomN);
        kingdomN.setBounds(10, 100, 170, 30);

        kingN.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        kingN.setText("king name");
        jPanel1.add(kingN);
        kingN.setBounds(10, 140, 120, 30);

        difficulty.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        difficulty.setText("Difficulty");
        jPanel1.add(difficulty);
        difficulty.setBounds(10, 200, 120, 30);

        easy.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        easy.setSelected(true);
        easy.setText("Easy");
        easy.setFocusable(false);
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });
        jPanel1.add(easy);
        easy.setBounds(130, 210, 60, 30);

        medium.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        medium.setText("Medium");
        medium.setFocusable(false);
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });
        jPanel1.add(medium);
        medium.setBounds(210, 210, 90, 30);

        hard.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        hard.setText("Hard");
        hard.setFocusable(false);
        hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardActionPerformed(evt);
            }
        });
        jPanel1.add(hard);
        hard.setBounds(320, 210, 70, 30);

        kingdomBox.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        kingdomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kingdomBoxActionPerformed(evt);
            }
        });
        jPanel1.add(kingdomBox);
        kingdomBox.setBounds(180, 100, 170, 30);
        kingdomBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(kingdomBox.getText().length()>=12&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    evt.consume();
                }
            }
        });

        kingBox.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jPanel1.add(kingBox);
        kingBox.setBounds(130, 140, 170, 30);
        kingBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if(kingBox.getText().length()>=12&&!(evt.getKeyChar()==KeyEvent.VK_DELETE||evt.getKeyChar()==KeyEvent.VK_BACK_SPACE)) {
                    evt.consume();
                }
            }
        });

        jButton1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton1.setText("TIME TO RULE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 320, 180, 40);

        titleSetup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/titles/kingdom.gamesetup.png"))); // NOI18N
        jPanel1.add(titleSetup);
        titleSetup.setBounds(70, 0, 420, 80);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/backs/castle-sky.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 565, 377);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //STOP MEDIEVAL MUSIC
        KingdomMenu.changeMusic(2);

        String king = kingBox.getText();
        if (king.length() > 0) {
            king = kingBox.getText();
            king = king.toLowerCase();
            king = king.substring(0, 1).toUpperCase() + king.substring(1).toLowerCase();
            if (king.contains(" ")) {
                king = king.substring(king.indexOf(" ") - 1, king.indexOf(" ")).toUpperCase() + king.substring(king.indexOf(" ")).toLowerCase();
            }
        } else {
            king = "Bob";
        }

        String kingdom = kingdomBox.getText();
        if (kingdom.length() > 0) {
            kingdom = kingdom.toLowerCase();
            kingdom = kingdom.substring(0, 1).toUpperCase() + kingdom.substring(1).toLowerCase();
            if (kingdom.contains(" ")) {
                kingdom = kingdom.substring(kingdom.indexOf(" ") - 1, kingdom.indexOf(" ")).toUpperCase() + kingdom.substring(kingdom.indexOf(" ")).toLowerCase();
            }
        } else {
            kingdom = "BobLand";
        }

        Variables.nameKing = king;
        Variables.nameKingdom = kingdom;

        if (easy.isSelected()) {
            Variables.Difficulty = 1;
            Variables.K_DayMS = 120_000;
        }
        if (medium.isSelected()) {
            Variables.Difficulty = 2;
            Variables.K_DayMS = 60_000;
        }
        if (hard.isSelected()) {
            Variables.Difficulty = 3;
            Variables.K_DayMS = 30_000;
        }

        //System.out.println("K_DayMS is " + Variables.K_DayMS);

        KingdomGame kGame = new KingdomGame();

        kGame.setBounds(this.getX() - 295, this.getY() - 130, 1200, 780);
        kGame.setVisible(true);

        kGame.setScrollTitle();

        dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void kingdomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kingdomBoxActionPerformed


    }//GEN-LAST:event_kingdomBoxActionPerformed

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed
        medium.setSelected(false);
        hard.setSelected(false);
        if (easy.isSelected() == false && medium.isSelected() == false && hard.isSelected() == false) {
            easy.setSelected(true);
        }

    }//GEN-LAST:event_easyActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed
        easy.setSelected(false);
        hard.setSelected(false);
        if (easy.isSelected() == false && medium.isSelected() == false && hard.isSelected() == false) {
            medium.setSelected(true);
        }
    }//GEN-LAST:event_mediumActionPerformed

    private void hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardActionPerformed
        easy.setSelected(false);
        medium.setSelected(false);
        if (easy.isSelected() == false && medium.isSelected() == false && hard.isSelected() == false) {
            hard.setSelected(true);
        }
    }//GEN-LAST:event_hardActionPerformed

    /**
     * @param args the command line arguments
     */
    KingdomMenu kMenu = new KingdomMenu();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel difficulty;
    public javax.swing.JCheckBox easy;
    public javax.swing.JCheckBox hard;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField kingBox;
    private javax.swing.JLabel kingN;
    public javax.swing.JTextField kingdomBox;
    private javax.swing.JLabel kingdomN;
    public javax.swing.JCheckBox medium;
    private javax.swing.JLabel titleSetup;
    // End of variables declaration//GEN-END:variables
}
