/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kingdom;


import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Eric
 */
public class KingdomMenu extends javax.swing.JFrame {

    /**
     * Creates new form KingdomMenu
     */
    public KingdomMenu() {

        initComponents();
        
        bird.start();
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonOptions = new javax.swing.JButton();
        buttonPlay = new javax.swing.JButton();
        labelKingdom = new javax.swing.JLabel();
        buttonHelp = new javax.swing.JButton();
        birdFlyer = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(395, 130, 0, 0));
        setFocusable(false);
        setResizable(false);

        jPanel1.setLayout(null);

        buttonOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/options.png"))); // NOI18N
        buttonOptions.setText("OPTIONS");
        buttonOptions.setFocusPainted(false);
        buttonOptions.setFocusable(false);
        buttonOptions.setMargin(new java.awt.Insets(0, 2, 0, -14));
        buttonOptions.setPreferredSize(new java.awt.Dimension(150, 74));
        buttonOptions.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/options.push.png"))); // NOI18N
        buttonOptions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/options.hov.png"))); // NOI18N
        buttonOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonOptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonOptionsMouseExited(evt);
            }
        });
        buttonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionsActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOptions);
        buttonOptions.setBounds(200, 200, 150, 70);

        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/play.png"))); // NOI18N
        buttonPlay.setText("PLAY");
        buttonPlay.setFocusPainted(false);
        buttonPlay.setMargin(new java.awt.Insets(0, 0, 0, -14));
        buttonPlay.setPreferredSize(new java.awt.Dimension(150, 70));
        buttonPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/play.push.png"))); // NOI18N
        buttonPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/play.hov.png"))); // NOI18N
        buttonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonPlayMouseExited(evt);
            }
        });
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPlay);
        buttonPlay.setBounds(200, 120, 150, 70);

        labelKingdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/titles/kingdom.title.png"))); // NOI18N
        labelKingdom.setFocusable(false);
        jPanel1.add(labelKingdom);
        labelKingdom.setBounds(70, 0, 410, 136);

        buttonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/help.png"))); // NOI18N
        buttonHelp.setText("HELP");
        buttonHelp.setFocusPainted(false);
        buttonHelp.setFocusable(false);
        buttonHelp.setMargin(new java.awt.Insets(0, 0, 0, -14));
        buttonHelp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/help.push.png"))); // NOI18N
        buttonHelp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/buttons/help.hov.png"))); // NOI18N
        buttonHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHelpMouseExited(evt);
            }
        });
        jPanel1.add(buttonHelp);
        buttonHelp.setBounds(200, 280, 150, 70);

        birdFlyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/birds/bird1.png"))); // NOI18N
        birdFlyer.setText("bird");
        jPanel1.add(birdFlyer);
        birdFlyer.setBounds(530, 120, 36, 28);
        birdFlyer.setVisible(false);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/backs/animate-castle.gif"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 565, 377);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseEntered
                mPlay.Hov();
    }//GEN-LAST:event_buttonPlayMouseEntered

    private void buttonOptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOptionsMouseEntered
                mPlay.Hov();
    }//GEN-LAST:event_buttonOptionsMouseEntered

    private void buttonHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMouseEntered
                mPlay.Hov();
                //REPAINTING IF NEEDED : 
//                        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/backs/castle.gif"))); // NOI18N
//                        jPanel1.revalidate(); jPanel1.repaint();
    }//GEN-LAST:event_buttonHelpMouseEntered

    private void buttonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionsActionPerformed
        

    }//GEN-LAST:event_buttonOptionsActionPerformed

    private void buttonPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseExited
        
    }//GEN-LAST:event_buttonPlayMouseExited

    private void buttonOptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOptionsMouseExited

    }//GEN-LAST:event_buttonOptionsMouseExited

    private void buttonHelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMouseExited

    }//GEN-LAST:event_buttonHelpMouseExited

    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed

    GameSetup gSetup = new GameSetup();
    
    gSetup.setBounds(this.getBounds());
    gSetup.setVisible(true);

    dispose();

    }//GEN-LAST:event_buttonPlayActionPerformed
                            

    /**
     * @param args the command line arguments
     */
    


    static MusicPlayer mPlay = new MusicPlayer();
    static KingdomMenu mMenu = new KingdomMenu();
    
    


    


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            public void run() {
                changeMusic(1);


                new KingdomMenu().setVisible(true);
                


                
            }
        });
    }
    
static public void changeMusic(int i){
    mPlay.MusicTypePlay=i;
    if(i==1){MedievalMusic.start();}
    if(i==2){SpringMusic.start();}
}
    
static public void stopMusic(){
    //STOP MEDIEVAL MUSIC
        mPlay.stop();
        
}
    
static Thread MedievalMusic = new Thread(new Runnable() {
     public void run() {   
        mPlay.run();
     }

});    
static Thread SpringMusic = new Thread(new Runnable() {
     public void run() {   
        mPlay.run();
     }

});    
         
Thread bird = new Thread(new Runnable() {
   
 public void run() {   
        
                
        try {        

            while(!(jPanel1 == null)){
//                System.out.println(jPanel1);
            bird.sleep(200);
         ranBird(true,1,false); 
            bird.sleep(130);
         ranBird(false,2,false); 
            bird.sleep(130);
         ranBird(false,3,false); 
            bird.sleep(130);
            for (int i = 0; i < 6; i++) {
         ranBird(false,1,false); 
            bird.sleep(130);
         ranBird(false,2,false); 
            bird.sleep(130);
         ranBird(false,3,false); 
            bird.sleep(130);  
            }
            long num = (long)((Math.random()+1)*10000);
            bird.sleep(num);
}
        } catch (InterruptedException ex) {
            Logger.getLogger(KingdomMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }        



});    


    int ranY;
    public void ranBird(boolean start, int birdN, boolean end) {
        
        if(start==true){       
        ranY = (int) (Math.round(Math.random()*265));

        birdFlyer.setBounds(jPanel1.getX()+550, jPanel1.getY()+(ranY), birdFlyer.getWidth(), birdFlyer.getHeight());
        birdFlyer.setVisible(true);
        }
        else if(end==true){
        birdFlyer.setVisible(false);}
        if(birdN==1){birdFlyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/birds/bird1.png")));}
        if(birdN==2){birdFlyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/birds/bird2.png")));}
        if(birdN==3){birdFlyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/birds/bird3.png")));}
        if(start==false){
        birdFlyer.setBounds(birdFlyer.getX()-30, jPanel1.getY()+(ranY), birdFlyer.getWidth(), birdFlyer.getHeight());}
    }
    



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel birdFlyer;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonOptions;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelKingdom;
    // End of variables declaration//GEN-END:variables
}
