/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kingdom;

import com.sun.corba.se.spi.orbutil.threadpool.ThreadPool;
import java.io.File;
import java.util.Set;
import javax.swing.ImageIcon;

/**
 *
 * @author Eric
 */
public class KingdomMenu extends javax.swing.JFrame {

    /**
     * Creates new form KingdomMenu
     */
    public KingdomMenu() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonOptions = new javax.swing.JButton();
        buttonPlay = new javax.swing.JButton();
        labelKingdom = new javax.swing.JLabel();
        buttonHelp = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jPanel1.setLayout(null);

        buttonOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/options.png"))); // NOI18N
        buttonOptions.setText("OPTIONS");
        buttonOptions.setFocusPainted(false);
        buttonOptions.setFocusable(false);
        buttonOptions.setMargin(new java.awt.Insets(0, 2, 0, -14));
        buttonOptions.setPreferredSize(new java.awt.Dimension(150, 74));
        buttonOptions.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/options.push.png"))); // NOI18N
        buttonOptions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/options.hov.png"))); // NOI18N
        buttonOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonOptionsMouseEntered(evt);
            }
        });
        jPanel1.add(buttonOptions);
        buttonOptions.setBounds(200, 200, 150, 70);

        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/play.png"))); // NOI18N
        buttonPlay.setText("PLAY");
        buttonPlay.setFocusPainted(false);
        buttonPlay.setMargin(new java.awt.Insets(0, 0, 0, -14));
        buttonPlay.setPreferredSize(new java.awt.Dimension(150, 70));
        buttonPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/play.push.png"))); // NOI18N
        buttonPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/play.hov.png"))); // NOI18N
        buttonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonPlayMouseEntered(evt);
            }
        });
        jPanel1.add(buttonPlay);
        buttonPlay.setBounds(200, 120, 150, 70);

        labelKingdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/kingdom.title.png"))); // NOI18N
        labelKingdom.setText("jLabel1");
        labelKingdom.setFocusable(false);
        jPanel1.add(labelKingdom);
        labelKingdom.setBounds(70, 0, 410, 136);

        buttonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/help.png"))); // NOI18N
        buttonHelp.setText("HELP");
        buttonHelp.setFocusPainted(false);
        buttonHelp.setFocusable(false);
        buttonHelp.setMargin(new java.awt.Insets(0, 0, 0, -14));
        buttonHelp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/help.push.png"))); // NOI18N
        buttonHelp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/help.hov.png"))); // NOI18N
        buttonHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHelpMouseEntered(evt);
            }
        });
        jPanel1.add(buttonHelp);
        buttonHelp.setBounds(200, 280, 150, 70);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/animate-castle.gif"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 565, 377);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseEntered
                mPlay.Hov();
                
    }//GEN-LAST:event_buttonPlayMouseEntered

    private void buttonOptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOptionsMouseEntered
                mPlay.Hov();
    }//GEN-LAST:event_buttonOptionsMouseEntered

    private void buttonHelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHelpMouseEntered
                mPlay.Hov();

                    Set<Thread> threadSet = Thread.getAllStackTraces().keySet();
                    Thread[] threadArray = threadSet.toArray(new Thread[threadSet.size()]);
                    
                    System.out.println(Thread.activeCount());

                    
                    
                //REPAINTING IF NEEDED : 
//                        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kingdom/images/castle.gif"))); // NOI18N
//                        jPanel1.revalidate(); jPanel1.repaint();
    }//GEN-LAST:event_buttonHelpMouseEntered
                            

    /**
     * @param args the command line arguments
     */
    
    

    static MusicPlayer mPlay = new MusicPlayer();
    static KingdomMenu mMenu = new KingdomMenu();
    
    
    


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KingdomMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mPlay.run();



                new KingdomMenu().setVisible(true);
            }
        });
    }
    



    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonOptions;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelKingdom;
    // End of variables declaration//GEN-END:variables
}
